// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnPX3wXv2XS13szescOYSkjeRUHT_iS4E',
    appId: '1:90501329716:web:4b5811b3adc488e5512b61',
    messagingSenderId: '90501329716',
    projectId: 'pertumbuhan-f58c4',
    authDomain: 'pertumbuhan-f58c4.firebaseapp.com',
    storageBucket: 'pertumbuhan-f58c4.firebasestorage.app',
    measurementId: 'G-BWFTHKTT2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9_cGTKfK2Fg_uwJhfxDkOx9e5PLSIXDY',
    appId: '1:90501329716:android:442205658737f2c0512b61',
    messagingSenderId: '90501329716',
    projectId: 'pertumbuhan-f58c4',
    storageBucket: 'pertumbuhan-f58c4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnPX3wXv2XS13szescOYSkjeRUHT_iS4E',
    appId: '1:90501329716:web:319148e2caf33353512b61',
    messagingSenderId: '90501329716',
    projectId: 'pertumbuhan-f58c4',
    authDomain: 'pertumbuhan-f58c4.firebaseapp.com',
    storageBucket: 'pertumbuhan-f58c4.firebasestorage.app',
    measurementId: 'G-70L2E03B0N',
  );
}
